### ISSUE TITLE
Wake up using API (AIS-1625)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-sr#101]
Instead of letting user speak the wake word, I need to wake up the wakenet in code, so that user can directly speak command word without speaking wake word temporarily. Is there such kind of API?

**Comment by feizi** [comment]
Speech command recognition and wake word recognition are independent of each other. I think you can trigger command recognition at any time, regardless of whether it has been woken up.

**Comment by mike-2020** [comment]
yes, it works perfect.

Is there a way to control timeout at runtime? I mean, after multinet is created, modify the timeout value ...

**Comment by feizi** [comment]
> Is there a way to control timeout at runtime? I mean, after multinet is created, modify the timeout value ...

There is no such API yet
