### ISSUE TITLE
Linker Fails (undefined reference to `esp_afe_vc_v1') (AIS-1629)

### ISSUE THREAD

**Issue by ZawarKhan97** [espressif/esp-sr#103]
afe_handle = (esp_afe_sr_iface_t *)&ESP_AFE_VC_HANDLE;

**Comment by sun-xiangyu** [comment]
Please refer to the esp-skainet/examples/voice_communication example. I tested it and it works fine. Currently, it supports the esp-idf v5.1.

**Comment by ZawarKhan97** [comment]
Thanks you were right..It currently supports ESP-IDF..I was using Platform.io
