### ISSUE TITLE
Ringbuffer Creation issue (AIS-1631)

### ISSUE THREAD

**Issue by ZawarKhan97** [espressif/esp-sr#105]
Hi, I testing Voice Communication example on esp32s3devkitc1. When during configuration load it gives me error ring buffer not created memory extenuated. Even i increase or reduce ring buffer size afe_config.afe_ringbuf_size = 100.. Help would be appreciated

Multiplayer Started!
I (368) AFE_VC: afe interface for voice communication

I (378) AFE_VC: AFE version: VC_V220727

W (378) SR_SYS: CPU freq should be 240MHz
W (388) SR_SYS: PSRAM freq should be not less than 80MHz
W (388) SR_SYS: Data cache recommends 64KB
W (398) SR_SYS: Data cache line recommends 64B
I (398) AFE_VC: Initial auido front-end, total channel: 1, mic num: 1, ref num: 0

I (408) AFE_VC: aec_init: 0, se_init: 1, vad_init: 0

I (418) AFE_VC: wakenet_init: 0, voice_communication_agc_init: 1

I (418) AFE_VC: ns_mode: 0

E (428) SR_RINGBUF: ./components/dl_lib/sr_ringbuf.c:87 (sr_rb_create): Memory exhausted
I (528) AFE_VC: mode: 0, (Feb 28 2024 20:11:45)

**Comment by ZawarKhan97** [comment]
when i use this afe_handle->reset_buffer(&afe_config);  before afe_data = afe_handle->create_from_config(&afe_config);..It does not give me memory exhaustion error..But it still goes to error of guru mediation error core 0 Paniced

**Comment by ZawarKhan97** [comment]
@sun-xiangyu  Kindly help..sorry for my manners

**Comment by feizi** [comment]
Please print your memory, including Internal ram and psram. I suspect that the remaining free memory is not enough.

**Comment by ZawarKhan97** [comment]
@feizi  thanks. Memory was the issue. I found out the spiram config wasnt done. I fixed it by enabling it in menuconfig. However i still get rb_out slow error. I will try to resolve it  I am not good that much ..

**Comment by feizi** [comment]
Hi @ZawarKhan97 , I suggest you use the default kconfig in [examples ](https://github.com/espressif/esp-skainet/blob/master/examples/en_speech_commands_recognition/sdkconfig.defaults.esp32s3) of esp-skainet.

**Comment by ZawarKhan97** [comment]
Thanks I have done atlast completed VC example with i2s read mic and i2s speaker. The issues resolved when i configured PSRAM and partition size to custom in menuconfig..

**Comment by feizi** [comment]
The configuration of PSRAM affects the read and write speed of PSRAM, which will significantly affect the speed of the esp-sr.
If the memory is slow or the CPU load is heavy, some audio frames may be dropped. Sometimes the audio quality will sound worse.

**Comment by ZawarKhan97** [comment]
@feizi  Thanksalot.. I understood the concept. And have successfully implemented Voice communication audio loop back from I2s mic to I2s speaker with AEC,VAD, NS, and AGC enabled. It works pretty good on EP32S3DevkitC1 . Thanks for your contribution.
