### ISSUE TITLE
parameter size of multinet

### ISSUE THREAD

**Issue by xdcesc** [espressif/esp-sr#12]
Any information about the parameter size of multinet for about 100 speech command recognition?

**Comment by feizi** [comment]
about 700K

**Comment by xdcesc** [comment]
@feizi How many layers of CNN and RNN used?

**Comment by xdcesc** [comment]
For quantised WakeNet6 with 378 K parameters, why only 45 KB RAM is used? if using 8-bit quantization, the parameters should occupy 378kB memory, so what is the trick?

**Comment by feizi** [comment]
model parameters is in flash
