### ISSUE TITLE
TypeError: find_apps() got an unexpected keyword argument (AIS-1719)

### ISSUE THREAD

**Issue by LingHsvan** [espressif/esp-sr#121]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

Unable to execute build_apps.py script to build the test

无法按照文档执行测试流程

### Actual behavior (suspected bug)

![image](https://github.com/user-attachments/assets/b99f314d-7b9a-4b2f-8720-68a2497e06f9)

### Error logs or terminal output

```shell
C:\Espressif\frameworks\esp-sr>python test_apps/build_apps.py test_apps -t esp32s3
C:\Espressif\frameworks\esp-sr
Traceback (most recent call last):
  File "C:\Espressif\frameworks\esp-sr\test_apps\build_apps.py", line 160, in <module>
    main(arguments)
  File "C:\Espressif\frameworks\esp-sr\test_apps\build_apps.py", line 77, in main
    apps = get_cmake_apps(args.paths, args.target, args.config, default_build_targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Espressif\frameworks\esp-sr\test_apps\build_apps.py", line 56, in get_cmake_apps
    apps = find_apps(
           ^^^^^^^^^^
TypeError: find_apps() got an unexpected keyword argument 'build_log_path'
```

### Steps to reproduce the behavior

```python
python test_apps/build_apps.py test_apps -t esp32s3
```
[link](https://github.com/espressif/esp-sr/blob/394aae67b578cf45ed13dad9c2e0c428f5d599f0/test_apps/README.md)

### Project release version

master

### System architecture

x86-64 / arm64

### Operating system

Windows / Raspberry Pi OS

### Operating system version

Windows 11 23H2 / Debian 12

### Shell

CMD / zsh

### Additional context

I executed the command on Windows and Raspberry Pi 5 according to the documentation steps, and exported different versions of the IDF environment, and the error message was the same.

我在Windows上和树莓派5上按照文档步骤执行命令，加载了不同版本的IDF环境，都是一样的报错信息

**Comment by sun-xiangyu** [comment]
The version of build_idf_app in build_app.py is quite old and does not support 2.0 and above. Please refer to [.gitlab-ci.yml](https://github.com/espressif/esp-sr/blob/master/.gitlab-ci.yml#L26C1-L26C37)
```
 pip install idf_build_apps==1.1.4
```
