### ISSUE TITLE
Typo in KConfig

### ISSUE THREAD

**Issue by holubcsongor** [espressif/esp-sr#13]
When running menuconfig, we got a warning, that the default choice is not in the list.
It is the same as in https://github.com/espressif/esp-sr/issues/11 (but i can't reopen it).
The related line in the KConfig is line 88.
(Branch master (latest), source commit: 724abeacad115fe3a4cd6db362365616d53ed206 )

Thank you for your help.

**Comment by feizi** [comment]
This is indeed a wrong configuration for WakeNet6.
