### ISSUE TITLE
Feature request: In speech recognition, pass detected phoneme to callbackfunction

### ISSUE THREAD

**Issue by bluelu** [espressif/esp-sr#14]
Hi,

For the speech detection, would it be possible to pass each detected phoneme (together with their probabilities?) to a callback function, which is triggered for each processed frame?

One could then stream those phonemes to a server which could do a more advanced command recognition.

At the moment, all the commands have to be predefined which is more focussed on stand alone devices.  

Not sure though if this is possible though technically since it's a binary library currently.

Thanks

**Comment by feizi** [comment]
In fact, if one can upload data to the server, I suggest he streams the microphone data to server directly.

**Comment by bluelu** [comment]
That was my backup plan as well. I will do it like that then. Thank you.
