### ISSUE TITLE
关于“命令词识别流程”的一些问题

### ISSUE THREAD

**Issue by iamweiweishi** [espressif/esp-sr#20]
你好，
请教一下关于命令词识别流程的一点疑问：
1：MultiNet似乎是参考的CRNN，但是我从CRNN原文中未找到关于音素（phoneme）的相关说明，想问一下，这里的音素是啥，能够举个例子；
2：语言模型是有什么作用，能够也举个例子。
谢谢

**Comment by feizi** [comment]
中文的音素就是拼音，语言模型的作用参考https://en.wikipedia.org/wiki/Finite-state_transducer

**Comment by iamweiweishi** [comment]
> 中文的音素就是拼音，语言模型的作用参考https://en.wikipedia.org/wiki/Finite-state_transducer

感谢回复。
也就是说语音首先经过某个模型，将语音识别到拼音，这个模型小且轻，可off-line运行；最后通过语言模型FST转到文字，进行最终的匹配，理解对么？
非常感谢。

**Comment by feizi** [comment]
可以转文字匹配，也可以不转文字直接匹配
