### ISSUE TITLE
English TTS in the works?

### ISSUE THREAD

**Issue by expresspotato** [espressif/esp-sr#22]
Is there an English version of ESP-TTS in the works?

**Comment by feizi** [comment]
We already have an initial version and are still optimizing. If your needs are urgent, we recommend you to use [flite](https://github.com/festvox/flite)

**Comment by truedat101** [comment]
Has anyone performed a flite integration on the ESP32 ADF platform ?  If there are projects it would be great if someone could post here.

**Comment by mmackh** [comment]
Has there been any developments recently?

**Comment by feizi** [comment]
Hi @mmackh , this [English TTS project on esp32](https://github.com/DiUS/esp-picotts) may can help you.

**Comment by mmackh** [comment]
Thank you for the info 🙏
