### ISSUE TITLE
Feature Request : Import wake words from other open source projects (AIS-778)

### ISSUE THREAD

**Issue by obones** [espressif/esp-sr#32]
ESP-SR currently only supports wake words in Chinese or English, while other open source projects support multiple other languages. For instance, there is the porcupine project: https://github.com/Picovoice/porcupine/tree/master/resources

I thus believe it would be nice to have the ability to import those models into the ESP-SR WakeNet format

**Comment by feizi** [comment]
Now our main goal is to continue to optimize Chinese and English model. In the future, we plan to support more languages.
