### ISSUE TITLE
Build error (AIS-855)

### ISSUE THREAD

**Issue by eyewy** [espressif/esp-sr#34]
When trying:
idf.py menuconfig
or
idf.py build
I get the following error:
CMake Error at CMakeLists.txt:45 (elseif):
  given arguments:

    "STREQUAL" "esp32s2"

  Unknown arguments specified

**Comment by feizi** [comment]
This repository is just a component and cannot be compiled directly.
Please try  [esp-skainet/examples](https://github.com/espressif/esp-skainet/tree/master/examples)
