### ISSUE TITLE
tts_parser would crash if it cannot find input words in voice data set (AIS-870)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-sr#36]
Hello,

I got this error when input "ni3 hao3". I'd suggest that return an error code instead of crashing the system.

_E (159060) tts_parser: Fail to search ni3 hao3 in voice set xiaole

assert failed: esp_tts_utt_append esp_tts_parser.c:92 (syll_idx>=0)_

**Comment by feizi** [comment]
The input format should be Chinese characters(utf-8), like ”你好“.
