### ISSUE TITLE
Can ESP provide some generic wake words？ (AIS-872)

### ISSUE THREAD

**Issue by balanceTWK** [espressif/esp-sr#38]

**Comment by balanceTWK** [comment]
Or offer some ways to train wake words.

**Comment by feizi** [comment]
We plan to collect more corpus in order to provide more wake words. Which words do you think are more generic wake words?

**Comment by balanceTWK** [comment]
> We plan to collect more corpus in order to provide more wake words. Which words do you think are generic wake words?

@feizi 

Chinese： "智能管家"；“语音助手”；“AI 管家”；such non-personalized wake words.

**Comment by sohotcall** [comment]
@feizi
English: "computer"

**Comment by feizi** [comment]
Hi @sohotcall , We are reducing the cost of wake word training. When we finish this, we will post more wake words for free.

**Comment by mike-2020** [comment]
Most of the commercial ASR chips/modules support wakeup word custermization at build/compile time. Some of them even supports wakeup words self-learning at runtime. 

Does ESP-SR have plan to support similar capability?

**Comment by feizi** [comment]
> Most of the commercial ASR chips/modules support wakeup word custermization at build/compile time. Some of them even supports wakeup words self-learning at runtime.

We have to make a choice between a very low-memory KWS and a customizable KWS. Currently, wakenet9(our latest wake model) parameter is about 250KB. It is difficult for this model to customize a new wake word using a few samples.

Now, our solution is to generate a large number of samples by TTS to customize the wake word. For community developers, we will collect some favorite wake words and regularly release these wake word models based on our capabilities. These models can be used commercially for free.

**Comment by feizi** [comment]
Now we can provide more generic wake words by TTS samples.

**Comment by feizi** [comment]
Hi all, now we can provide some generic wake words by TTS samples.
