### ISSUE TITLE
hijeson 唤醒词支持 (AIS-876)

### ISSUE THREAD

**Issue by hnhkj** [espressif/esp-sr#39]
我看到esp-sr是支持hijeson的，我如何和实现这个唤醒词？

**Comment by feizi** [comment]
1. 现在hijeson唤醒词在临时分支　[feature/reduce_mn5en_delay](https://github.com/espressif/esp-sr/tree/feature/reduce_mn5en_delay)　上，你可以切换到该临时分支　　
　
2. 拷贝　./model/wakenet_model/hijeson8/*　文件覆盖你当前工程　./model/wakenet_model/hilexin8/　文件，这样你就可以在menuconfig中选择wakenet8/hilexin 16bit 选择使用　hijeson

3. 后续我们会将新版hijeson合并到master

**Comment by hnhkj** [comment]
Hi feizi
我使用的是esp32_lyraT，是否可以支持hijeson唤醒词？我按照你的方法进行测试没有成功。

**Comment by feizi** [comment]
现在针对esp32，我们基本停止更新了。
esp32s3具有AI加速指令，可以运行更大的模型，同时占用更少的资源，请切换到esp32s3相关开发板
