### ISSUE TITLE
工程编译环境是 esp-adf 吗？麻烦提供下？想做产品；

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-sr#4]
- 工程编译环境是 esp-adf 吗？麻烦提供下编译流程？想做产品；上个月有客户要做定制化本地语音识别模块，这个支持离线唤醒么？

**Comment by feizi** [comment]
esp-idf和esp-adf都可以
编译流程 可以参考工程 [esp-skainet](https://github.com/espressif/esp-skainet)
支持离线唤醒

**Comment by xuhongv** [comment]
好的。明白！
