### ISSUE TITLE
crash when creating a multinet model (AIS-878)

### ISSUE THREAD

**Issue by Gojok** [espressif/esp-sr#41]
I am using ESP32-WROVER-E and ESP-IDF v4.2.3, multinet2.
Crash occurs when trying to call multinet->create().

static const esp_mn_iface_t *multinet = &MULTINET_MODEL;
printf("------------multinet create------------\n");
model_iface_data_t *model_data = multinet->create(&MULTINET_COEFF, 2048); // <-- crash 
printf("------------detect reset------------\n");

LOG:
rst:0xc (SW_CPU_RESET),boot:0x1f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7052
ho 0 tail 12 room 4
load:0x40078000,len:13200
load:0x40080400,len:4584
entry 0x400806f4
I (29) boot: ESP-IDF v4.2.3 2nd stage bootloader
I (29) boot: compile time 16:21:01
I (29) boot: chip revision: 1
I (32) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (43) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 16MB
I (53) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 factory          factory app      00 00 00010000 00500000
I (76) boot: End of partition table
I (80) boot_comm: chip revision: 1, min. application chip revision: 0
I (88) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x140c54 (1313876) map
I (597) esp_image: segment 1: paddr=0x00150c7c vaddr=0x3ffb0000 size=0x021b0 (  8624) load
I (601) esp_image: segment 2: paddr=0x00152e34 vaddr=0x40080000 size=0x0aee4 ( 44772) load
I (623) esp_image: segment 3: paddr=0x0015dd20 vaddr=0x00000000 size=0x022f8 (  8952) 
I (627) esp_image: segment 4: paddr=0x00160020 vaddr=0x400d0020 size=0x1cba0 (117664) map
I (680) boot: Loaded app from partition at offset 0x10000
I (681) boot: Disabling RNG early entropy source...
I (681) cpu_start: Pro cpu up.
I (685) cpu_start: Application information:
I (689) cpu_start: Project name:     wake_word_detection
I (695) cpu_start: App version:      v0.3.0-105-g4847f52-dirty
I (702) cpu_start: Compile time:     May 20 2022 16:20:40
I (708) cpu_start: ELF file SHA256:  35f293a763fba85a...
I (714) cpu_start: ESP-IDF:          v4.2.3
I (719) cpu_start: Starting app cpu, entry point is 0x4008166c
I (711) cpu_start: App cpu up.
I (730) heap_init: Initializing. RAM available for dynamic allocation:
I (736) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (742) heap_init: At 3FFB2E28 len 0002D1D8 (180 KiB): DRAM
I (749) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (755) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (761) heap_init: At 4008AEE4 len 0001511C (84 KiB): IRAM
I (768) cpu_start: Pro cpu start user code
I (786) spi_flash: detected chip: generic
I (786) spi_flash: flash io: dio
I (787) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
------------multinet create------------
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d5018  PS      : 0x00060130  A0      : 0x800d3c7c  A1      : 0x3ffb79d0  
A2      : 0xffffffff  A3      : 0xffffffff  A4      : 0x00000000  A5      : 0x0000004b  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x800d5018  A9      : 0x3ffb79b0  
A10     : 0x00000000  A11     : 0x3ffb7a20  A12     : 0x00000030  A13     : 0x3ffb6a44  
A14     : 0x00000016  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000004  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

Backtrace:0x400d5015:0x3ffb79d0 0x400d3c79:0x3ffb79f0 0x400d3dd0:0x3ffb7ad0 0x400d3235:0x3ffb7af0 0x400854b1:0x3ffb7be0

ELF file SHA256: 35f293a763fba85a

Rebooting...

**Comment by feizi** [comment]
Please try esp-sr v1.4.0 again.
