### ISSUE TITLE
Is psram necessary for esp32 or esp32s3 to run esp-sr?  (AIS-1012)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-sr#49]
Hi ,if I wanna run esp-sr on esp32 or esp32s3, is the psram necessary?
If it does need psram,How big it requires?
Is 2MB psram enough?
Thanks!

**Comment by feizi** [comment]
Yes, it does need psram.
Different model need different sizes of psram. You can refer to [performance_test](https://github.com/espressif/esp-sr/tree/master/docs/performance_test) to get a specific amount of memory for your task.
