### ISSUE TITLE
Missing esp_tts_voice_female.h (AIS-1015)

### ISSUE THREAD

**Issue by babadue** [espressif/esp-sr#51]
I tried to compile the example in the README, but got the error because it could not location this "esp_tts_voice_female.h”.   What did I miss?

**Comment by feizi** [comment]
The "esp_tts_voice_female.h" is replaced by  "esp_tts_voice_xiaole.h".
I'm sorry for not updating the document in time.
Please refer to [esp-tts-example](https://github.com/espressif/esp-skainet/tree/master/examples/chinese_tts) for more details.

**Comment by babadue** [comment]
谢谢！
