### ISSUE TITLE
Question about Load Multple wake words (AIS-1017)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-sr#52]
很抱歉我的英语有些差，不能够用英文来完美描述这个问题，所以采用中文，请见谅！
我使用ESPS3-BOX测试了“Load Multple wake words”这个功能，我选择了Hi，lexin，和xiaoaitongxue两个命令词，但是只有Hi,lexin可以成功唤醒，而xiaoaitongxue不可以，请问是这个样子吗？
所以说这个“Load Multple wake words”的功能是同时支持多个唤醒词，还是说每次支持一个唤醒词，想要切换的话需要在代码里面切换呢？
再次感谢！

**Comment by feizi** [comment]
是的，需要在代码中切换。
可以参考
https://github.com/espressif/esp-sr/blob/55a37b51b96cf41289ac3536bb5750a6a1412cb4/include/esp32s3/esp_afe_sr_iface.h#L112-L120
