### ISSUE TITLE
如何延长语音唤醒后的等待时间？ (AIS-1106)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-sr#59]
语音唤醒之后，大概6s左右，就会退出listening。请问怎么修改可以使得listening的时间变长呢？
谢谢！

**Comment by feizi** [comment]
```
multinet->create(model_name, duration)
```
duration，单位ms, 就是触发timeout的时长,目前multinet5及以后的模型都支持修改

**Comment by casitelwithdean** [comment]
> ```
> multinet->create(model_name, duration)
> ```
> 
> duration，单位ms, 就是触发timeout的时长,目前multinet5及以后的模型都支持修改

十分感谢！
