### ISSUE TITLE
是不是普通的ESP32-WRoom 无法使用 SR? (AIS-1171)

### ISSUE THREAD

**Issue by xxlxmd** [espressif/esp-sr#66]
普通的ESP32-wroom-32U 搭配I2C麦克风 是不是无法使用 SR 以及 skainet? ESP32CAM呢?

最低支持的板子是什么呢?Korvo? EYE 还是 KIT? 感觉成本都非常高啊

**Comment by feizi** [comment]
主要的问题是ESP32模组只能支持ESP-SR部分功能, 推荐ESP32-S3的模组和相关开发板
