### ISSUE TITLE
c++ wakeword example

### ISSUE THREAD

**Issue by Romkabouter** [espressif/esp-sr#7]
Hi, 

Is it possible to provide an example using c++?

I have created a c++ program which is calling the wakeNet.
This compiles and runs ok, but when I call:
int r = wakenet->detect(model_data, buffer);
I get this error message:

Fail: index is out of range, the min index is 1, the max index is 1

**Comment by feizi** [comment]
That error message may appear in function `set_det_threshold`, `get_det_threshould`,`get_word_name`, instead of `detect` when parameter `index` value is error.    
So please check the parameter `index` first.

**Comment by Romkabouter** [comment]
I am using the exact Task as used in https://github.com/espressif/esp-sr/blob/master/main/wakenet_test.c

What is the index parameter in that testcase?
The call  int frequency = wakenet->get_samp_rate(model_data); works as expected.

When I comment out the detect call, I do not get an error message

**Comment by feizi** [comment]
It is strange, I will test wakenet by C++.

**Comment by Romkabouter** [comment]
Additional request that if it is not an issue, a sample project can be pushed to github?
Thanks in advance

**Comment by Romkabouter** [comment]
Hi feizi, did you already have time to look into this issue?

**Comment by feizi** [comment]
I do not get the above error message when I test wakenet by C++.

1. modify the main/main.c to main/main.cpp, 
2. modify main function:
```
extern "C" {
void app_main()
{
    // test wakenet
    wakenet_test();
    vTaskDelay(3000 / portTICK_PERIOD_MS);

}
}
```
3. modify ./main/include/wakenet_test.h
```
#pragma once
#ifdef _cpulspuls
extern "C" {
#endif

void wakenet_test();

#ifdef _cplusplus
}
#endif
```
4. make flash

**Comment by Romkabouter** [comment]
Thank you, I have got the test working now. 
I am dutch and I do not speak Chinese, is it possible to include a wav file from the hilexin.h in order to hear how the wakeword should be spoken?
