### ISSUE TITLE
esp_afe_sr_1mic被移除后ESP32S3-EYE应该怎么进行语音识别 (AIS-1285)

### ISSUE THREAD

**Issue by Kevincoooool** [espressif/esp-sr#73]
发现最新版本的esp-sr移除了esp_afe_sr_1mic，然后用最新的代码就不能识别了，现在针对ESP32S3-EYE这块板子需要做什么配置才能识别到？

**Comment by sun-xiangyu** [comment]
新的版本可以直接通过afe_config 设置麦克风的数量，是向下兼容1mic的，具体可以参考 [esp-skainet 里的设置](https://github.com/espressif/esp-skainet/blob/a9429c33cf4a2e9f8b610eb0abb676dede23f59f/examples/cn_speech_commands_recognition/main/main.c#L164)
```
        afe_config.pcm_config.total_ch_num = 2;
        afe_config.pcm_config.mic_num = 1;
        afe_config.pcm_config.ref_num = 1;
```
