### ISSUE TITLE
Missing flite_g2p.h for esp32 (AIS-1408)

### ISSUE THREAD

**Issue by tore-espressif** [espressif/esp-sr#82]
Missing [flite_g2p.h](https://github.com/espressif/esp-sr/blob/master/include/esp32s3/flite_g2p.h) for esp32 breaks compilation

Problem exists only on version  1.5.0

**Comment by sun-xiangyu** [comment]
Thanks @tore-espressif , the bug has been fixed.
And I add a ci test for esp32 chip to avoid something like this.

**Comment by tore-espressif** [comment]
@sun-xiangyu thank you for the fast response!

Is there a plan to release v1.5.1? And yank broken version 1.5.0?

**Comment by feizi** [comment]
v1.5.1 has been released.
