### ISSUE TITLE
Can 4-mic circular array be supported?

### ISSUE THREAD

**Issue by feelkit** [espressif/esp-sr#9]
Multi-mic array processing, including multi-mic AEC and noise suppression. Can 4-mic circular array be supported?

**Comment by yangz-zju** [comment]
Hi, as stated in ReadMe, currently only 2/3-mic arrays are supported. This limitation is due to the number of i2s peripherals supported by our released hardware. We'll release software supporting 4(or more)-mic arrays with corresponding hardware in the future, please stay tuned :)
