### ISSUE TITLE
Suitable for non-human sound recognition? (AIS-1503)

### ISSUE THREAD

**Issue by gamename** [espressif/esp-sr#91]
Hi,

Is it possible to use this package for identifying non-human sounds? I'm looking for a way to recognize cat sounds.  I have the model, but I don't know what ESP library to use.  

Could AFE be used for this?

Any suggestions would be appreciated.

**Comment by shenxiaozheng** [comment]
I understand that you need to trigger a device when a cat makes a sound, similar to Amazon's smart speakers with the wake-up word "Alexa." However, AFE does not have the wake-up word "meow," so you hope to provide an audio sample of a cat meowing for wake word model training.

**Comment by gamename** [comment]
> > I have the model, but I don't know what ESP library to use.
> 
> Hi @gamename , If you want to deploy your own model on ESP chip, please refer to [esp-dl](https://github.com/espressif/esp-dl). This project may help you.

Thank you!
