### ISSUE TITLE
Building error when used in platformIO/ESPHome context (AIS-1527)

### ISSUE THREAD

**Issue by X-Ryl669** [espressif/esp-sr#92]
When used in ESPHome context (for Home Assistant mainly), any version later than [this commit](https://github.com/espressif/esp-sr/commit/e1c73a59d94fe5d656c83788c9cec619e8f5070a) fails CMake to build on this line
`idf_component_get_property(esp_dsp_lib espressif__esp-dsp COMPONENT_LIB)`

This is because `espressif__esp-dsp` isn't defined so CMake choke on bad number of argument to the `idf_component_get_property`, it see 2 arguments instead of 3.

I do have a `__idf_esp-dsp` variable, but not a `espressif__esp-dsp` variable. I'm able to successfully pass this step if I just replace that line with `set(esp_dsp_lib "esp-dsp")`

**Comment by X-Ryl669** [comment]
@igrr I don't know how the `espressif__esp-dsp` is created (maybe there's an additional step to perform here that I didn't). Do you have an idea?

**Comment by igrr** [comment]
Could you please describe how you add esp-sr to your project?

Perhaps you could also attach the build log of a clean (failing) build, as well as the (successful) build log after the modification you made?
