### ISSUE TITLE
ESP-IDF version compatibility (AIS-1538)

### ISSUE THREAD

**Issue by PrathamG** [espressif/esp-sr#94]
Hi! Esp-Skainet readme mentions that it is only compatible with EDFv5.0 . 
Is there the same limitation with ESP-SR or can SR be used with master branch of IDF?
Thanks!

**Comment by sun-xiangyu** [comment]
I have not tested the master branch. But I think esp-sr should be compatible with esp-idf master branch because esp-sr only relies on a portion of the flash APIs, which have not been modified.
