### ISSUE TITLE
NSNET ESP-SR (AIS-1581)

### ISSUE THREAD

**Issue by dnambinh** [espressif/esp-sr#98]
what is different between NSNET1 vs NSNET2?(noise filtering performance and additional features (output amplification?)?

**Comment by shenxiaozheng** [comment]
> what is different between NSNET1 vs NSNET2?(noise filtering performance and additional features (output amplification?)?

Compared to nsnet1, nsnet2 has a moderate reduction in CPU usage, but an increase in MOS value of 16%. It achieves better noise reduction ability at lower CPU usage.

**Comment by shenxiaozheng** [comment]
Nsnet2 has much lower CPU usage than nsnet1, but its MOS value has increased by 16%. It achieves better noise reduction ability at lower CPU usage.

**Comment by dnambinh** [comment]
> Nsnet2 has much lower CPU usage than nsnet1, but its MOS value has increased by 16%. It achieves better noise reduction ability at lower CPU usage.

I have not tested the performance of CPU or RAM usage, but it is clear that when using 2 mic mems, nsnet1 is more effective, nsnet2 causes sound distortion. I wonder if there is any difference in setting up afe or i2s between these two networks?

**Comment by shenxiaozheng** [comment]
My testing standard is the MOS value, which is an internationally recognized standard, Nsnet2 has better performance. How did you test for distortion? There is no difference in i2s.

**Comment by dnambinh** [comment]
> My testing standard is the MOS value, which is an internationally recognized standard, Nsnet2 has better performance. How did you test for distortion? There is no difference in i2s.

Simply listen and compare with input. Maybe I'll test more with our speech to text model, if it translates then there's no problem. As an additional note, using NS_MODE_SSP mode is also quite good, but I still want to improve the input quality.
I will come back after completing the test. Thank for your infor

**Comment by shenxiaozheng** [comment]
If you are using it for a very simple scenario, I highly recommend using SSP mode.

**Comment by dnambinh** [comment]
Currently I use MODE SSP and everything is relatively fine so I will close this issue, thank you very much

**Comment by shenxiaozheng** [comment]
Thank you very much for using our library and for your valuable suggestions. We will continue to optimize and hope to bring you a better experience.
